version: 2

sources:
  - name: github
    database: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
    schema: "{{ env_var('BQ_DATASET', 'github_activity') }}"
    tables:
      - name: github_events
        description: "Raw GitHub events"
        columns:
          - name: event_id
            tests: [not_null]
          - name: created_at
            tests: [not_null]
